
# GetAll pessoas
GET http://localhost:3000/pessoas

###

# Get Pesssoa by Id
GET http://localhost:3000/pessoas/1






###
# Create pessoa
POST http://localhost:3000/pessoas
Content-Type: application/json

    {
        "nome":"Francieli de Almeida",
        "endereco":{
            "rua": "Rua Porto Alegre",
            "cidade": "Curitiba" 
        }
    }



  

