
# GetAll the pessoas
GET http://localhost:3000/pessoas

###

# Create a pessoa
POST http://localhost:3000/pessoas
Content-Type: application/json

    {
        "nome":"Ana Giseli",
        "endereco":{
            "rua": "Rua das Flores",
            "cidade": "Slo" 
        }
    }
  

